// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/activity" | "/dashboard/billing/cancel" | "/dashboard/billing/history" | "/dashboard/billing/payment-methods" | "/dashboard/billing/payment-methods/edit" | "/dashboard/billing/plans" | "/dashboard/calendar" | "/dashboard/calendar/day/[date]" | "/dashboard/events" | "/dashboard/events/[id]" | "/dashboard/events/[id]/analytics" | "/dashboard/events/[id]/attendees" | "/dashboard/events/[id]/attendees/[attendeeId]" | "/dashboard/events/[id]/cancel" | "/dashboard/events/[id]/edit" | "/dashboard/events/[id]/schedule/edit" | "/dashboard/events/[id]/speakers/[speakerId]" | "/dashboard/events/[id]/speakers/add" | "/dashboard/events/[id]/team" | "/dashboard/events/[id]/tickets/manage" | "/dashboard/events/[id]/tickets/types" | "/dashboard/events/[id]/tickets/types/[typeId]/edit" | "/dashboard/events/[id]/tickets/types/create" | "/dashboard/events/create" | "/dashboard/logout" | "/dashboard/profile" | "/dashboard/settings" | "/dashboard/tickets" | "/dashboard/tickets/[id]" | "/dashboard/tickets/[id]/edit" | "/dashboard/tickets/scan" | "/dashboard/users" | "/dashboard/users/[id]" | "/dashboard/users/[id]/deactivate" | "/dashboard/users/[id]/edit" | "/dashboard/users/[id]/permissions" | "/landing" | "/login" | "/register"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/dashboard/activity": {}
  "/dashboard/billing/cancel": {}
  "/dashboard/billing/history": {}
  "/dashboard/billing/payment-methods": {}
  "/dashboard/billing/payment-methods/edit": {}
  "/dashboard/billing/plans": {}
  "/dashboard/calendar": {}
  "/dashboard/calendar/day/[date]": { "date": string; }
  "/dashboard/events": {}
  "/dashboard/events/[id]": { "id": string; }
  "/dashboard/events/[id]/analytics": { "id": string; }
  "/dashboard/events/[id]/attendees": { "id": string; }
  "/dashboard/events/[id]/attendees/[attendeeId]": { "id": string; "attendeeId": string; }
  "/dashboard/events/[id]/cancel": { "id": string; }
  "/dashboard/events/[id]/edit": { "id": string; }
  "/dashboard/events/[id]/schedule/edit": { "id": string; }
  "/dashboard/events/[id]/speakers/[speakerId]": { "id": string; "speakerId": string; }
  "/dashboard/events/[id]/speakers/add": { "id": string; }
  "/dashboard/events/[id]/team": { "id": string; }
  "/dashboard/events/[id]/tickets/manage": { "id": string; }
  "/dashboard/events/[id]/tickets/types": { "id": string; }
  "/dashboard/events/[id]/tickets/types/[typeId]/edit": { "id": string; "typeId": string; }
  "/dashboard/events/[id]/tickets/types/create": { "id": string; }
  "/dashboard/events/create": {}
  "/dashboard/logout": {}
  "/dashboard/profile": {}
  "/dashboard/settings": {}
  "/dashboard/tickets": {}
  "/dashboard/tickets/[id]": { "id": string; }
  "/dashboard/tickets/[id]/edit": { "id": string; }
  "/dashboard/tickets/scan": {}
  "/dashboard/users": {}
  "/dashboard/users/[id]": { "id": string; }
  "/dashboard/users/[id]/deactivate": { "id": string; }
  "/dashboard/users/[id]/edit": { "id": string; }
  "/dashboard/users/[id]/permissions": { "id": string; }
  "/landing": {}
  "/login": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
