// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/dashboard/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/activity">> = Specific
  const handler = {} as typeof import("../../app/dashboard/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing/cancel">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/payment-methods/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing/payment-methods/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/payment-methods/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/payment-methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing/payment-methods">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/payment-methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing/plans">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/calendar/day/[date]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar/day/[date]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/calendar/day/[date]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/calendar">> = Specific
  const handler = {} as typeof import("../../app/dashboard/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/analytics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/attendees/[attendeeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/attendees/[attendeeId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/attendees/[attendeeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/attendees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/attendees">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/attendees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/schedule/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/schedule/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/schedule/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/speakers/[speakerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/speakers/[speakerId]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/speakers/[speakerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/speakers/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/speakers/add">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/speakers/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/team">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/tickets/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/tickets/manage">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/tickets/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/tickets/types/[typeId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/tickets/types/[typeId]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/tickets/types/[typeId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/tickets/types/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/tickets/types/create">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/tickets/types/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/[id]/tickets/types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/tickets/types">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/[id]/tickets/types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/create">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logout">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tickets/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tickets/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tickets/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tickets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tickets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tickets">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tickets/scan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tickets/scan">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tickets/scan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/[id]/deactivate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]/deactivate">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/[id]/deactivate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/[id]/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]/permissions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/[id]/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
